name: Run tests

on: pull_request

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.6
        with:
          unityVersion: 2019.3.8f1
          customParameters: -enableCodeCoverage -coverageResultsPath '"/home/runner/work/HangmanGame/HangmanGame/artifacts/CodeCoverage/"' -coverageOptions '"generateHtmlReport;assemblyFilters:+*Hangman*,-*unity*,-*Tests*"'
      
      - name: Save Test Result Artifacts 
        uses: actions/upload-artifact@v1
        with:
            name: Test results
            path: artifacts
  code-coverage:
    name: Test coverage
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Load Test Result Artifacts 
        uses: actions/download-artifact@v1
        with:
            name: Test results
            path: artifacts
      - shell: bash
        run: cat /home/runner/work/HangmanGame/HangmanGame/artifacts/CodeCoverage/Report/Summary.xml

      - name: Check Code Coverage
        uses: AnImaginedReality/UnityCodeCoverage.Action@v0.0.4
        with:
          required-coverage: 99 #test
          coverage-file-path: /home/runner/work/HangmanGame/HangmanGame/artifacts/CodeCoverage/Report/Summary.xml
