name: Run tests

on: pull_request

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.3.0f1
          customParameters: -enableCodeCoverage -coverageOptions enableCyclomaticComplexity;generateHtmlReport;generateBadgeReport;assemblyFilters:+*Hangman.*,-Tests*

      - name: SonarQube analysis
        if: always()
        uses: MirrorNG/unity-runner@2.0.0
        with:
          solution: /github/workspace/workspace.sln
          projectKey: DanielParra159_HangmanGame
          projectName: HangmanGame
          sonarOrganisation: danielparra159
          beginArguments: /d:sonar.verbose="true"
        env:
          FrameworkPathOverride: /opt/Unity/Editor/Data/MonoBleedingEdge/
          UNITY_LICENSE: ${{ secrets.U_LICENSE }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

