name: Sonar

on: 
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.md'
  
jobs:    
  static-analyzer:
    name: Main
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    if: true
    steps:
  
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install filter-repo
        run: pip3 install git-filter-repo
              
              
      # Test
      - name: Generate Solution
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.3.8f1
          customParameters: -buildTarget StandaloneWindows64 -customBuildPath ./build/StandaloneWindows64 -executeMethod UnityEditor.SyncVS.SyncSolution -quit

      - name: SonarQube analysis
        if: always()
        uses: MirrorNG/unity-runner@2.0.0
        with:
          projectKey: DanielParra159_HangmanGame
          projectName: HangmanGame
          sonarOrganisation: danielparra159
          unityVersion: 2019.3.8f1
          beginArguments: /d:sonar.verbose="true"
          solution: /github/workspace/workspace.sln
        env:
          FrameworkPathOverride: /opt/Unity/Editor/Data/MonoBleedingEdge/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
